development: &defaults
  identifier: 8ba3106a401baeba350a3845aad792df
  secret: 2eb1378e960577e67ee238b650c59cb2a8528f8c194ad7429f1068832d078ba6
  scope: email profile address PPID
  host: op.dev
  scheme: http
  authorization_endpoint: /authorizations/new
  token_endpoint: /access_tokens
  check_session_endpoint: /id_token
  user_info_endpoint: /user_info
  public_key_endpoint: /public.crt

test:
  <<: *defaults

production:
  <<: *defaults
  identifier: 10e151158cb45988d98758c489bc0424
  secret: 63805108fa6ba35cb27f55cff1cfa4603f0ab80e744e7be0e91eb8dcd69c2150
  host: connect-op.heroku.com
  scheme: https