development: &defaults
  identifier: 8ba3106a401baeba350a3845aad792df
  secret: 2eb1378e960577e67ee238b650c59cb2a8528f8c194ad7429f1068832d078ba6
  scope: email profile address PPID
  host: op.dev
  scheme: http
  authorization_endpoint: /authorizations/new
  token_endpoint: /access_tokens
  check_session_endpoint: /id_token
  user_info_endpoint: /user_info
  public_key_endpoint: /public.crt

test:
  <<: *defaults

production:
  <<: *defaults
  identifier: d36b87830791a037fabf32625bf90865
  secret: 2c1fb5d90b1066275290871e74aeed656afc1aeccc8fec4196aa726381bffff1
  host: connect-op.heroku.com
  scheme: https