development: &defaults
  identifier: 8ba3106a401baeba350a3845aad792df
  secret: 2eb1378e960577e67ee238b650c59cb2a8528f8c194ad7429f1068832d078ba6
  scope: email profile address PPID
  host: op.dev
  scheme: http
  authorization_endpoint: /authorizations/new
  token_endpoint: /access_tokens
  check_session_endpoint: /id_token
  user_info_endpoint: /user_info
  public_key_endpoint: /public.crt

test:
  <<: *defaults

production:
  <<: *defaults
  identifier: bf7b2e0507fe26a16f74befd64da4ee9
  secret: 529d616574f628550e21c831d5926e824ed684ea68052fd34286aff429e14526
  host: connect-op.heroku.com
  scheme: https